development:
  adapter: mysql
  encoding: utf8
  host: 140.254.80.125
  database: depthmap
  pool: 5
  username: depthmap
  password: map

test:
  adapter: mysql
  encoding: utf8
  host: 140.254.80.125
  database: depthmap
  pool: 5
  username: depthmap
  password: map

production:
  adapter: mysql
  encoding: utf8
  host: 140.254.80.125
  database: depthmap
  pool: 5
  username: depthmap
  password: map
