development:
  adapter: mysql
  encoding: utf8
  database: pointmap
  pool: 5
  username: pointmap
  password: point.map!

test:
  adapter: mysql
  encoding: utf8
  database: pointmap
  pool: 5
  username: pointmap
  password: point.map!

production:
  adapter: mysql
  encoding: utf8
  database: pointmap
  pool: 5
  username: pointmap
  password: point.map!
